image: python:2

stages:
    - lint
    - build

cpplint:
    stage: lint
    script:
        - "pip install cpplint"
        - "find libopus.cpp/src -regex '.*\\.\\(cpp\\|h\\)' | xargs cpplint"

makeall:
    variables: 
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script:
        - "cd libopus.cpp && make"
    only: 
        - web