image: python:2

stages:
    - lint
    - build

cpplint:
    stage: lint
    script:
        - "pip install cpplint"
        - "find libopus.cpp/src -regex '.*\\.\\(cpp\\|h\\)' | xargs cpplint"

makeall:
    stage: build
    script:
        - "make"
    only: 
        - master