[package]
name = "pvm-data"
version = "0.2.0"
authors = ["Thomas Bytheway <tb403@cam.ac.uk>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
built = "0.3"

[dependencies]
uuid = "0.7"
chrono = { version = ">=0.4.3", features = ["serde"] }
serde = "*"
serde_derive = "*"
