[package]
name = "pvm-views"
version = "0.1.0"
authors = ["Thomas Bytheway <tb403@cam.ac.uk>"]
edition = "2018"

[dependencies]
pvm-data = { path = "../pvm-data" }
quick-error = { package = "quick-error2", version = "2" }