[package]
name = "pvm-views"
version = "0.2.0"
authors = ["Thomas Bytheway <tb403@cam.ac.uk>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
built = "0.3"

[dependencies]
pvm-data = { path = "../pvm-data" }
quick-error = { package = "quick-error2", version = "2" }